services:
  worker:
    environment:
      WORKER_VIDEO_DEVICES: "/dev/video10,/dev/video11,/dev/video12,/dev/video13"
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
      - "/dev/video13:/dev/video13"
